# ======================================================================
# R Analysis Script for: Clinical Interactions & Trainee Well-Being
# Generated by Prism v0.5.0 on 2026-01-05 22:52:17
# ======================================================================

# This script provides a complete analysis pipeline including:
#   - Data import and cleaning
#   - Descriptive statistics
#   - Reliability analysis (Cronbach's alpha)
#   - Data visualization
#   - Quality checks and filtering

# ======================================================================
# SETUP: Install Required Packages
# ======================================================================

# Uncomment to install packages (run once):
# install.packages(c('tidyverse', 'psych', 'ggplot2', 'patchwork'))

# Load libraries
library(tidyverse)  # Data manipulation and visualization
library(psych)      # Reliability analysis
library(ggplot2)    # Advanced plotting
library(patchwork)  # Combine plots

# ======================================================================
# DATA IMPORT
# ======================================================================

# Import processed data
data <- read_csv('examples/test_r.csv')
cat('\n=== Data Overview ===\n')
glimpse(data)

# ======================================================================
# QUALITY FILTERING
# ======================================================================

# Examine quality flags
cat('\n=== Quality Check Summary ===\n')
table(data$quality_flag)

# Display flagged records
flagged <- data %>% filter(quality_flag == 'FLAGGED')
cat(sprintf('Flagged records: %d (%.1f%%)\n', 
    nrow(flagged), 100 * nrow(flagged) / nrow(data)))

if (nrow(flagged) > 0) {
  cat('\nReasons for flagging:\n')
  print(table(flagged$quality_reason))
}

# Create clean dataset
clean_data <- data %>% filter(quality_flag == 'OK')
cat(sprintf('\nClean records: %d (%.1f%%)\n', 
    nrow(clean_data), 100 * nrow(clean_data) / nrow(data)))

# ======================================================================
# DESCRIPTIVE STATISTICS
# ======================================================================

# peer_support (4 items)
cat('\n=== peer_support Statistics ===\n')
clean_data %>%
  select(peer_support_mean) %>%
  summary() %>%
  print()

# Standard deviation
sd_val <- sd(clean_data$peer_support_mean, na.rm = TRUE)
cat(sprintf('SD: %.2f\n', sd_val))

# supervision_rapport (12 items)
cat('\n=== supervision_rapport Statistics ===\n')
clean_data %>%
  select(supervision_rapport_mean) %>%
  summary() %>%
  print()

# Standard deviation
sd_val <- sd(clean_data$supervision_rapport_mean, na.rm = TRUE)
cat(sprintf('SD: %.2f\n', sd_val))

# depersonalization (5 items)
cat('\n=== depersonalization Statistics ===\n')
clean_data %>%
  select(depersonalization_mean) %>%
  summary() %>%
  print()

# Standard deviation
sd_val <- sd(clean_data$depersonalization_mean, na.rm = TRUE)
cat(sprintf('SD: %.2f\n', sd_val))

# alliance_total (12 items)
cat('\n=== alliance_total Statistics ===\n')
clean_data %>%
  select(alliance_total_mean) %>%
  summary() %>%
  print()

# Standard deviation
sd_val <- sd(clean_data$alliance_total_mean, na.rm = TRUE)
cat(sprintf('SD: %.2f\n', sd_val))

# emotional_exhaustion (9 items)
cat('\n=== emotional_exhaustion Statistics ===\n')
clean_data %>%
  select(emotional_exhaustion_mean) %>%
  summary() %>%
  print()

# Standard deviation
sd_val <- sd(clean_data$emotional_exhaustion_mean, na.rm = TRUE)
cat(sprintf('SD: %.2f\n', sd_val))

# ======================================================================
# RELIABILITY ANALYSIS (Cronbach's Alpha)
# ======================================================================

# Reliability for peer_support
cat('\n=== peer_support Reliability ===\n')
peer_support_items <- clean_data %>% select(MSPSS_1, MSPSS_2, MSPSS_3, MSPSS_4)
peer_support_alpha <- alpha(peer_support_items)
print(peer_support_alpha, digits = 3)

# Reliability for supervision_rapport
cat('\n=== supervision_rapport Reliability ===\n')
supervision_rapport_items <- clean_data %>% select(SWAI_1, SWAI_2, SWAI_3, SWAI_4, SWAI_5, SWAI_6, SWAI_7, SWAI_8, SWAI_9, SWAI_10, SWAI_11, SWAI_12)
supervision_rapport_alpha <- alpha(supervision_rapport_items)
print(supervision_rapport_alpha, digits = 3)

# Reliability for depersonalization
cat('\n=== depersonalization Reliability ===\n')
depersonalization_items <- clean_data %>% select(Q10, Q11, Q12, Q13, Q14)
depersonalization_alpha <- alpha(depersonalization_items)
print(depersonalization_alpha, digits = 3)

# Reliability for alliance_total
cat('\n=== alliance_total Reliability ===\n')
alliance_total_items <- clean_data %>% select(WAI_1, WAI_2, WAI_3, WAI_4, WAI_5, WAI_6, WAI_7, WAI_8, WAI_9, WAI_10, WAI_11, WAI_12)
alliance_total_alpha <- alpha(alliance_total_items)
print(alliance_total_alpha, digits = 3)

# Reliability for emotional_exhaustion
cat('\n=== emotional_exhaustion Reliability ===\n')
emotional_exhaustion_items <- clean_data %>% select(Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q9)
emotional_exhaustion_alpha <- alpha(emotional_exhaustion_items)
print(emotional_exhaustion_alpha, digits = 3)

# ======================================================================
# DATA VISUALIZATION
# ======================================================================

# Distribution plots for scales
p1 <- ggplot(clean_data, aes(x = peer_support_mean)) +
  geom_histogram(binwidth = 0.5, fill = 'steelblue', color = 'black', alpha = 0.7) +
  geom_vline(aes(xintercept = mean(peer_support_mean, na.rm = TRUE)), 
             color = 'red', linetype = 'dashed', size = 1) +
  labs(title = 'peer_support', x = 'Mean Score', y = 'Frequency') +
  theme_minimal()

p2 <- ggplot(clean_data, aes(x = supervision_rapport_mean)) +
  geom_histogram(binwidth = 0.5, fill = 'steelblue', color = 'black', alpha = 0.7) +
  geom_vline(aes(xintercept = mean(supervision_rapport_mean, na.rm = TRUE)), 
             color = 'red', linetype = 'dashed', size = 1) +
  labs(title = 'supervision_rapport', x = 'Mean Score', y = 'Frequency') +
  theme_minimal()

p3 <- ggplot(clean_data, aes(x = depersonalization_mean)) +
  geom_histogram(binwidth = 0.5, fill = 'steelblue', color = 'black', alpha = 0.7) +
  geom_vline(aes(xintercept = mean(depersonalization_mean, na.rm = TRUE)), 
             color = 'red', linetype = 'dashed', size = 1) +
  labs(title = 'depersonalization', x = 'Mean Score', y = 'Frequency') +
  theme_minimal()

p4 <- ggplot(clean_data, aes(x = alliance_total_mean)) +
  geom_histogram(binwidth = 0.5, fill = 'steelblue', color = 'black', alpha = 0.7) +
  geom_vline(aes(xintercept = mean(alliance_total_mean, na.rm = TRUE)), 
             color = 'red', linetype = 'dashed', size = 1) +
  labs(title = 'alliance_total', x = 'Mean Score', y = 'Frequency') +
  theme_minimal()

p5 <- ggplot(clean_data, aes(x = emotional_exhaustion_mean)) +
  geom_histogram(binwidth = 0.5, fill = 'steelblue', color = 'black', alpha = 0.7) +
  geom_vline(aes(xintercept = mean(emotional_exhaustion_mean, na.rm = TRUE)), 
             color = 'red', linetype = 'dashed', size = 1) +
  labs(title = 'emotional_exhaustion', x = 'Mean Score', y = 'Frequency') +
  theme_minimal()

# Combine plots
combined_plot <- p1 + p2 + p3 + p4 + p5
print(combined_plot)

# Save plot
ggsave('scale_distributions.png', combined_plot, width = 12, height = 8, dpi = 300)

# Box plot: Compare flagged vs clean data
p_box_peer_support <- ggplot(data, aes(x = quality_flag, y = peer_support_mean, fill = quality_flag)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = c('OK' = 'lightgreen', 'FLAGGED' = 'salmon')) +
  labs(title = 'peer_support by Quality Flag', x = 'Quality Flag', y = 'Mean Score') +
  theme_minimal() +
  theme(legend.position = 'none')
print(p_box_peer_support)

p_box_supervision_rapport <- ggplot(data, aes(x = quality_flag, y = supervision_rapport_mean, fill = quality_flag)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = c('OK' = 'lightgreen', 'FLAGGED' = 'salmon')) +
  labs(title = 'supervision_rapport by Quality Flag', x = 'Quality Flag', y = 'Mean Score') +
  theme_minimal() +
  theme(legend.position = 'none')
print(p_box_supervision_rapport)

p_box_depersonalization <- ggplot(data, aes(x = quality_flag, y = depersonalization_mean, fill = quality_flag)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = c('OK' = 'lightgreen', 'FLAGGED' = 'salmon')) +
  labs(title = 'depersonalization by Quality Flag', x = 'Quality Flag', y = 'Mean Score') +
  theme_minimal() +
  theme(legend.position = 'none')
print(p_box_depersonalization)

p_box_alliance_total <- ggplot(data, aes(x = quality_flag, y = alliance_total_mean, fill = quality_flag)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = c('OK' = 'lightgreen', 'FLAGGED' = 'salmon')) +
  labs(title = 'alliance_total by Quality Flag', x = 'Quality Flag', y = 'Mean Score') +
  theme_minimal() +
  theme(legend.position = 'none')
print(p_box_alliance_total)

p_box_emotional_exhaustion <- ggplot(data, aes(x = quality_flag, y = emotional_exhaustion_mean, fill = quality_flag)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = c('OK' = 'lightgreen', 'FLAGGED' = 'salmon')) +
  labs(title = 'emotional_exhaustion by Quality Flag', x = 'Quality Flag', y = 'Mean Score') +
  theme_minimal() +
  theme(legend.position = 'none')
print(p_box_emotional_exhaustion)

# ======================================================================
# CORRELATION MATRIX (if multiple scales)
# ======================================================================

# Select scale means
scale_means <- clean_data %>% select(peer_support_mean, supervision_rapport_mean, depersonalization_mean, alliance_total_mean, emotional_exhaustion_mean)

# Correlation matrix
cat('\n=== Correlation Matrix ===\n')
cor_matrix <- cor(scale_means, use = 'pairwise.complete.obs')
print(round(cor_matrix, 2))

# Correlation plot
library(corrplot)
corrplot(cor_matrix, method = 'circle', type = 'upper', 
         addCoef.col = 'black', tl.col = 'black', tl.srt = 45)

# ======================================================================
# EXPORT RESULTS
# ======================================================================

# Save clean dataset
write_csv(clean_data, 'clean_data_r.csv')

# Create summary table
summary_stats <- clean_data %>% summarise(
  'peer_support_M' = mean(peer_support_mean, na.rm = TRUE),
  'peer_support_SD' = sd(peer_support_mean, na.rm = TRUE),
  'peer_support_Min' = min(peer_support_mean, na.rm = TRUE),
  'peer_support_Max' = max(peer_support_mean, na.rm = TRUE), 
  'supervision_rapport_M' = mean(supervision_rapport_mean, na.rm = TRUE),
  'supervision_rapport_SD' = sd(supervision_rapport_mean, na.rm = TRUE),
  'supervision_rapport_Min' = min(supervision_rapport_mean, na.rm = TRUE),
  'supervision_rapport_Max' = max(supervision_rapport_mean, na.rm = TRUE), 
  'depersonalization_M' = mean(depersonalization_mean, na.rm = TRUE),
  'depersonalization_SD' = sd(depersonalization_mean, na.rm = TRUE),
  'depersonalization_Min' = min(depersonalization_mean, na.rm = TRUE),
  'depersonalization_Max' = max(depersonalization_mean, na.rm = TRUE), 
  'alliance_total_M' = mean(alliance_total_mean, na.rm = TRUE),
  'alliance_total_SD' = sd(alliance_total_mean, na.rm = TRUE),
  'alliance_total_Min' = min(alliance_total_mean, na.rm = TRUE),
  'alliance_total_Max' = max(alliance_total_mean, na.rm = TRUE), 
  'emotional_exhaustion_M' = mean(emotional_exhaustion_mean, na.rm = TRUE),
  'emotional_exhaustion_SD' = sd(emotional_exhaustion_mean, na.rm = TRUE),
  'emotional_exhaustion_Min' = min(emotional_exhaustion_mean, na.rm = TRUE),
  'emotional_exhaustion_Max' = max(emotional_exhaustion_mean, na.rm = TRUE)
)

cat('\n=== Summary Statistics Table ===\n')
print(summary_stats)

# Save summary table
write_csv(summary_stats, 'summary_statistics.csv')

cat('\n✓ Analysis complete! Results saved.\n')
