* ======================================================================
* SPSS Syntax for: Clinical Interactions & Trainee Well-Being
* Generated by Prism v0.3.0 on 2026-01-05 22:38:17
* ======================================================================

* This syntax file includes:
*   - Data import from CSV
*   - Variable labels and descriptions
*   - Value labels for response scales
*   - Reverse scoring transformations
*   - Scale computation (total and mean scores)
*   - Missing value declarations

* ======================================================================
* SECTION 1: DATA IMPORT
* ======================================================================

GET DATA
  /TYPE=TXT
  /FILE='examples/test_spss.csv'
  /ENCODING='UTF8'
  /DELIMITERS=","
  /QUALIFIER='"'
  /FIRSTCASE=2
  /IMPORTCASE=ALL
  /VARIABLES=
    * Items for scale: supervision_rapport
    SWAI_1 F8.0
    SWAI_2 F8.0
    SWAI_3 F8.0
    SWAI_4 F8.0
    SWAI_5 F8.0
    SWAI_6 F8.0
    SWAI_7 F8.0
    SWAI_8 F8.0
    SWAI_9 F8.0
    SWAI_10 F8.0
    SWAI_11 F8.0
    SWAI_12 F8.0
    * Items for scale: depersonalization
    Q10 F8.0
    Q11 F8.0
    Q12 F8.0
    Q13 F8.0
    Q14 F8.0
    * Items for scale: alliance_total
    WAI_1 F8.0
    WAI_2 F8.0
    WAI_3 F8.0
    WAI_4 F8.0
    WAI_5 F8.0
    WAI_6 F8.0
    WAI_7 F8.0
    WAI_8 F8.0
    WAI_9 F8.0
    WAI_10 F8.0
    WAI_11 F8.0
    WAI_12 F8.0
    * Items for scale: peer_support
    MSPSS_1 F8.0
    MSPSS_2 F8.0
    MSPSS_3 F8.0
    MSPSS_4 F8.0
    * Items for scale: emotional_exhaustion
    Q1 F8.0
    Q2 F8.0
    Q3 F8.0
    Q4 F8.0
    Q5 F8.0
    Q6 F8.0
    Q7 F8.0
    Q8 F8.0
    Q9 F8.0
    supervision_rapport_total F8.2
    supervision_rapport_mean F8.2
    depersonalization_total F8.2
    depersonalization_mean F8.2
    alliance_total_total F8.2
    alliance_total_mean F8.2
    peer_support_total F8.2
    peer_support_mean F8.2
    emotional_exhaustion_total F8.2
    emotional_exhaustion_mean F8.2
    quality_flag A50
    quality_reason A255
    .
EXECUTE.

* ======================================================================
* SECTION 2: VARIABLE LABELS
* ======================================================================

VARIABLE LABELS
  SWAI_1 'supervision_rapport - Item 1'
  SWAI_2 'supervision_rapport - Item 2'
  SWAI_3 'supervision_rapport - Item 3'
  SWAI_4 'supervision_rapport - Item 4'
  SWAI_5 'supervision_rapport - Item 5'
  SWAI_6 'supervision_rapport - Item 6'
  SWAI_7 'supervision_rapport - Item 7'
  SWAI_8 'supervision_rapport - Item 8'
  SWAI_9 'supervision_rapport - Item 9'
  SWAI_10 'supervision_rapport - Item 10'
  SWAI_11 'supervision_rapport - Item 11'
  SWAI_12 'supervision_rapport - Item 12'
  supervision_rapport_total 'supervision_rapport Total Score (12-84)'
  supervision_rapport_mean 'supervision_rapport Mean Score (1-7)'
  Q10 'depersonalization - Item 1'
  Q11 'depersonalization - Item 2'
  Q12 'depersonalization - Item 3'
  Q13 'depersonalization - Item 4'
  Q14 'depersonalization - Item 5'
  depersonalization_total 'depersonalization Total Score (5-35)'
  depersonalization_mean 'depersonalization Mean Score (1-7)'
  WAI_1 'alliance_total - Item 1'
  WAI_2 'alliance_total - Item 2'
  WAI_3 'alliance_total - Item 3'
  WAI_4 'alliance_total - Item 4 (reverse scored)'
  WAI_5 'alliance_total - Item 5'
  WAI_6 'alliance_total - Item 6'
  WAI_7 'alliance_total - Item 7'
  WAI_8 'alliance_total - Item 8'
  WAI_9 'alliance_total - Item 9'
  WAI_10 'alliance_total - Item 10 (reverse scored)'
  WAI_11 'alliance_total - Item 11'
  WAI_12 'alliance_total - Item 12'
  alliance_total_total 'alliance_total Total Score (12-84)'
  alliance_total_mean 'alliance_total Mean Score (1-7)'
  MSPSS_1 'peer_support - Item 1'
  MSPSS_2 'peer_support - Item 2'
  MSPSS_3 'peer_support - Item 3'
  MSPSS_4 'peer_support - Item 4'
  peer_support_total 'peer_support Total Score (4-28)'
  peer_support_mean 'peer_support Mean Score (1-7)'
  Q1 'emotional_exhaustion - Item 1'
  Q2 'emotional_exhaustion - Item 2'
  Q3 'emotional_exhaustion - Item 3'
  Q4 'emotional_exhaustion - Item 4'
  Q5 'emotional_exhaustion - Item 5'
  Q6 'emotional_exhaustion - Item 6'
  Q7 'emotional_exhaustion - Item 7'
  Q8 'emotional_exhaustion - Item 8'
  Q9 'emotional_exhaustion - Item 9'
  emotional_exhaustion_total 'emotional_exhaustion Total Score (9-63)'
  emotional_exhaustion_mean 'emotional_exhaustion Mean Score (1-7)'
  quality_flag 'Data Quality Flag'
  quality_reason 'Quality Issue Description'
  .
EXECUTE.

* ======================================================================
* SECTION 3: VALUE LABELS FOR RESPONSE SCALES
* ======================================================================

VALUE LABELS
  SWAI_1 SWAI_2 SWAI_3 SWAI_4 SWAI_5 SWAI_6 SWAI_7 SWAI_8 SWAI_9 SWAI_10 SWAI_11 SWAI_12 Q10 Q11 Q12 Q13 Q14 WAI_1 WAI_2 WAI_3 WAI_4 WAI_5 WAI_6 WAI_7 WAI_8 WAI_9 WAI_10 WAI_11 WAI_12 MSPSS_1 MSPSS_2 MSPSS_3 MSPSS_4 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9
  1 'Strongly Disagree'
  2 'Disagree'
  3 'Somewhat Disagree'
  4 'Neutral'
  5 'Somewhat Agree'
  6 'Agree'
  7 'Strongly Agree'
  .
EXECUTE.

VALUE LABELS quality_flag
  'OK' 'Passed all quality checks'
  'FLAGGED' 'Quality issues detected'
  .
EXECUTE.

* ======================================================================
* SECTION 4: MISSING VALUE DECLARATIONS
* ======================================================================

* Declare system missing for out-of-range values
IF (SWAI_1 < 1 OR SWAI_1 > 7) SWAI_1 = $SYSMIS.
IF (SWAI_2 < 1 OR SWAI_2 > 7) SWAI_2 = $SYSMIS.
IF (SWAI_3 < 1 OR SWAI_3 > 7) SWAI_3 = $SYSMIS.
IF (SWAI_4 < 1 OR SWAI_4 > 7) SWAI_4 = $SYSMIS.
IF (SWAI_5 < 1 OR SWAI_5 > 7) SWAI_5 = $SYSMIS.
IF (SWAI_6 < 1 OR SWAI_6 > 7) SWAI_6 = $SYSMIS.
IF (SWAI_7 < 1 OR SWAI_7 > 7) SWAI_7 = $SYSMIS.
IF (SWAI_8 < 1 OR SWAI_8 > 7) SWAI_8 = $SYSMIS.
IF (SWAI_9 < 1 OR SWAI_9 > 7) SWAI_9 = $SYSMIS.
IF (SWAI_10 < 1 OR SWAI_10 > 7) SWAI_10 = $SYSMIS.
IF (SWAI_11 < 1 OR SWAI_11 > 7) SWAI_11 = $SYSMIS.
IF (SWAI_12 < 1 OR SWAI_12 > 7) SWAI_12 = $SYSMIS.
IF (Q10 < 1 OR Q10 > 7) Q10 = $SYSMIS.
IF (Q11 < 1 OR Q11 > 7) Q11 = $SYSMIS.
IF (Q12 < 1 OR Q12 > 7) Q12 = $SYSMIS.
IF (Q13 < 1 OR Q13 > 7) Q13 = $SYSMIS.
IF (Q14 < 1 OR Q14 > 7) Q14 = $SYSMIS.
IF (WAI_1 < 1 OR WAI_1 > 7) WAI_1 = $SYSMIS.
IF (WAI_2 < 1 OR WAI_2 > 7) WAI_2 = $SYSMIS.
IF (WAI_3 < 1 OR WAI_3 > 7) WAI_3 = $SYSMIS.
IF (WAI_4 < 1 OR WAI_4 > 7) WAI_4 = $SYSMIS.
IF (WAI_5 < 1 OR WAI_5 > 7) WAI_5 = $SYSMIS.
IF (WAI_6 < 1 OR WAI_6 > 7) WAI_6 = $SYSMIS.
IF (WAI_7 < 1 OR WAI_7 > 7) WAI_7 = $SYSMIS.
IF (WAI_8 < 1 OR WAI_8 > 7) WAI_8 = $SYSMIS.
IF (WAI_9 < 1 OR WAI_9 > 7) WAI_9 = $SYSMIS.
IF (WAI_10 < 1 OR WAI_10 > 7) WAI_10 = $SYSMIS.
IF (WAI_11 < 1 OR WAI_11 > 7) WAI_11 = $SYSMIS.
IF (WAI_12 < 1 OR WAI_12 > 7) WAI_12 = $SYSMIS.
IF (MSPSS_1 < 1 OR MSPSS_1 > 7) MSPSS_1 = $SYSMIS.
IF (MSPSS_2 < 1 OR MSPSS_2 > 7) MSPSS_2 = $SYSMIS.
IF (MSPSS_3 < 1 OR MSPSS_3 > 7) MSPSS_3 = $SYSMIS.
IF (MSPSS_4 < 1 OR MSPSS_4 > 7) MSPSS_4 = $SYSMIS.
IF (Q1 < 1 OR Q1 > 7) Q1 = $SYSMIS.
IF (Q2 < 1 OR Q2 > 7) Q2 = $SYSMIS.
IF (Q3 < 1 OR Q3 > 7) Q3 = $SYSMIS.
IF (Q4 < 1 OR Q4 > 7) Q4 = $SYSMIS.
IF (Q5 < 1 OR Q5 > 7) Q5 = $SYSMIS.
IF (Q6 < 1 OR Q6 > 7) Q6 = $SYSMIS.
IF (Q7 < 1 OR Q7 > 7) Q7 = $SYSMIS.
IF (Q8 < 1 OR Q8 > 7) Q8 = $SYSMIS.
IF (Q9 < 1 OR Q9 > 7) Q9 = $SYSMIS.
EXECUTE.

* ======================================================================
* SECTION 5: REVERSE SCORING TRANSFORMATIONS
* ======================================================================

* Reverse scoring for alliance_total scale
RECODE WAI_4 (1 = 7) (7 = 1).
  (2 = 6) (3 = 5) (4 = 4) (5 = 3) (6 = 2) 
RECODE WAI_10 (1 = 7) (7 = 1).
  (2 = 6) (3 = 5) (4 = 4) (5 = 3) (6 = 2) 
EXECUTE.

* ======================================================================
* SECTION 6: SCALE SCORE COMPUTATION
* ======================================================================

* Compute supervision_rapport scale (12 items)
COMPUTE supervision_rapport_total = SWAI_1 + SWAI_2 + SWAI_3 + SWAI_4 + SWAI_5 + SWAI_6 + SWAI_7 + SWAI_8 + SWAI_9 + SWAI_10 + SWAI_11 + SWAI_12.
COMPUTE supervision_rapport_mean = MEAN(SWAI_1, SWAI_2, SWAI_3, SWAI_4, SWAI_5, SWAI_6, SWAI_7, SWAI_8, SWAI_9, SWAI_10, SWAI_11, SWAI_12).
EXECUTE.

* Compute depersonalization scale (5 items)
COMPUTE depersonalization_total = Q10 + Q11 + Q12 + Q13 + Q14.
COMPUTE depersonalization_mean = MEAN(Q10, Q11, Q12, Q13, Q14).
EXECUTE.

* Compute alliance_total scale (12 items)
COMPUTE alliance_total_total = WAI_1 + WAI_2 + WAI_3 + WAI_4 + WAI_5 + WAI_6 + WAI_7 + WAI_8 + WAI_9 + WAI_10 + WAI_11 + WAI_12.
COMPUTE alliance_total_mean = MEAN(WAI_1, WAI_2, WAI_3, WAI_4, WAI_5, WAI_6, WAI_7, WAI_8, WAI_9, WAI_10, WAI_11, WAI_12).
EXECUTE.

* Compute peer_support scale (4 items)
COMPUTE peer_support_total = MSPSS_1 + MSPSS_2 + MSPSS_3 + MSPSS_4.
COMPUTE peer_support_mean = MEAN(MSPSS_1, MSPSS_2, MSPSS_3, MSPSS_4).
EXECUTE.

* Compute emotional_exhaustion scale (9 items)
COMPUTE emotional_exhaustion_total = Q1 + Q2 + Q3 + Q4 + Q5 + Q6 + Q7 + Q8 + Q9.
COMPUTE emotional_exhaustion_mean = MEAN(Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q9).
EXECUTE.

* ======================================================================
* END OF SYNTAX
* ======================================================================

* To verify data:
DESCRIPTIVES VARIABLES=
  supervision_rapport_mean depersonalization_mean alliance_total_mean peer_support_mean emotional_exhaustion_mean
  /STATISTICS=MEAN STDDEV MIN MAX.

* Reliability analysis example:
RELIABILITY
  /VARIABLES=
    SWAI_1 SWAI_2 SWAI_3 SWAI_4 SWAI_5 SWAI_6 SWAI_7 SWAI_8 SWAI_9 SWAI_10 SWAI_11 SWAI_12
  /SCALE('supervision_rapport') ALL
  /MODEL=ALPHA.
