# ======================================================================
# Python Analysis Script for: Clinical Interactions & Trainee Well-Being
# Generated by Prism v0.5.0 on 2026-01-05 22:52:23
# ======================================================================

# This script provides a complete analysis pipeline including:
#   - Data import and cleaning
#   - Descriptive statistics
#   - Reliability analysis (Cronbach's alpha)
#   - Data visualization
#   - Quality checks and filtering

# ======================================================================
# SETUP: Install Required Packages
# ======================================================================

# Run once in terminal:
# pip install pandas numpy matplotlib seaborn pingouin scipy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pingouin as pg  # For Cronbach's alpha
from scipy import stats

# Set plot style
sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (12, 8)

# ======================================================================
# DATA IMPORT
# ======================================================================

# Import processed data
data = pd.read_csv('examples/test_python.csv')
print('\n=== Data Overview ===')
print(data.info())
print(f'\nShape: {data.shape[0]} rows × {data.shape[1]} columns')

# ======================================================================
# QUALITY FILTERING
# ======================================================================

# Examine quality flags
print('\n=== Quality Check Summary ===')
print(data['quality_flag'].value_counts())

# Display flagged records
flagged = data[data['quality_flag'] == 'FLAGGED']
print(f'\nFlagged records: {len(flagged)} ({100 * len(flagged) / len(data):.1f}%)')

if len(flagged) > 0:
    print('\nReasons for flagging:')
    print(flagged['quality_reason'].value_counts())

# Create clean dataset
clean_data = data[data['quality_flag'] == 'OK'].copy()
print(f'\nClean records: {len(clean_data)} ({100 * len(clean_data) / len(data):.1f}%)')

# ======================================================================
# DESCRIPTIVE STATISTICS
# ======================================================================

# depersonalization (5 items)
print('\n=== depersonalization Statistics ===')
print(clean_data['depersonalization_mean'].describe())

# supervision_rapport (12 items)
print('\n=== supervision_rapport Statistics ===')
print(clean_data['supervision_rapport_mean'].describe())

# emotional_exhaustion (9 items)
print('\n=== emotional_exhaustion Statistics ===')
print(clean_data['emotional_exhaustion_mean'].describe())

# peer_support (4 items)
print('\n=== peer_support Statistics ===')
print(clean_data['peer_support_mean'].describe())

# alliance_total (12 items)
print('\n=== alliance_total Statistics ===')
print(clean_data['alliance_total_mean'].describe())

# ======================================================================
# RELIABILITY ANALYSIS (Cronbach's Alpha)
# ======================================================================

# Reliability for depersonalization
print('\n=== depersonalization Reliability ===')
depersonalization_items = clean_data[['Q10', 'Q11', 'Q12', 'Q13', 'Q14']].dropna()
depersonalization_alpha = pg.cronbach_alpha(data=depersonalization_items)
print(f'Cronbach\'s Alpha: {depersonalization_alpha[0]:.3f}')
print(f'95% CI: [{ depersonalization_alpha[1][0]:.3f }, { depersonalization_alpha[1][1]:.3f }]')

# Reliability for supervision_rapport
print('\n=== supervision_rapport Reliability ===')
supervision_rapport_items = clean_data[['SWAI_1', 'SWAI_2', 'SWAI_3', 'SWAI_4', 'SWAI_5', 'SWAI_6', 'SWAI_7', 'SWAI_8', 'SWAI_9', 'SWAI_10', 'SWAI_11', 'SWAI_12']].dropna()
supervision_rapport_alpha = pg.cronbach_alpha(data=supervision_rapport_items)
print(f'Cronbach\'s Alpha: {supervision_rapport_alpha[0]:.3f}')
print(f'95% CI: [{ supervision_rapport_alpha[1][0]:.3f }, { supervision_rapport_alpha[1][1]:.3f }]')

# Reliability for emotional_exhaustion
print('\n=== emotional_exhaustion Reliability ===')
emotional_exhaustion_items = clean_data[['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9']].dropna()
emotional_exhaustion_alpha = pg.cronbach_alpha(data=emotional_exhaustion_items)
print(f'Cronbach\'s Alpha: {emotional_exhaustion_alpha[0]:.3f}')
print(f'95% CI: [{ emotional_exhaustion_alpha[1][0]:.3f }, { emotional_exhaustion_alpha[1][1]:.3f }]')

# Reliability for peer_support
print('\n=== peer_support Reliability ===')
peer_support_items = clean_data[['MSPSS_1', 'MSPSS_2', 'MSPSS_3', 'MSPSS_4']].dropna()
peer_support_alpha = pg.cronbach_alpha(data=peer_support_items)
print(f'Cronbach\'s Alpha: {peer_support_alpha[0]:.3f}')
print(f'95% CI: [{ peer_support_alpha[1][0]:.3f }, { peer_support_alpha[1][1]:.3f }]')

# Reliability for alliance_total
print('\n=== alliance_total Reliability ===')
alliance_total_items = clean_data[['WAI_1', 'WAI_2', 'WAI_3', 'WAI_4', 'WAI_5', 'WAI_6', 'WAI_7', 'WAI_8', 'WAI_9', 'WAI_10', 'WAI_11', 'WAI_12']].dropna()
alliance_total_alpha = pg.cronbach_alpha(data=alliance_total_items)
print(f'Cronbach\'s Alpha: {alliance_total_alpha[0]:.3f}')
print(f'95% CI: [{ alliance_total_alpha[1][0]:.3f }, { alliance_total_alpha[1][1]:.3f }]')

# ======================================================================
# DATA VISUALIZATION
# ======================================================================

# Distribution plots for scales (5 scales)
fig, axes = plt.subplots(3, 2, figsize=(12, 12))
axes = axes.flatten()

# Plot 1: depersonalization
axes[0].hist(clean_data['depersonalization_mean'].dropna(), bins=20, color='steelblue', edgecolor='black', alpha=0.7)
axes[0].axvline(clean_data['depersonalization_mean'].mean(), color='red', linestyle='dashed', linewidth=2, label='Mean')
axes[0].set_title('depersonalization')
axes[0].set_xlabel('Mean Score')
axes[0].set_ylabel('Frequency')
axes[0].legend()

# Plot 2: supervision_rapport
axes[1].hist(clean_data['supervision_rapport_mean'].dropna(), bins=20, color='steelblue', edgecolor='black', alpha=0.7)
axes[1].axvline(clean_data['supervision_rapport_mean'].mean(), color='red', linestyle='dashed', linewidth=2, label='Mean')
axes[1].set_title('supervision_rapport')
axes[1].set_xlabel('Mean Score')
axes[1].set_ylabel('Frequency')
axes[1].legend()

# Plot 3: emotional_exhaustion
axes[2].hist(clean_data['emotional_exhaustion_mean'].dropna(), bins=20, color='steelblue', edgecolor='black', alpha=0.7)
axes[2].axvline(clean_data['emotional_exhaustion_mean'].mean(), color='red', linestyle='dashed', linewidth=2, label='Mean')
axes[2].set_title('emotional_exhaustion')
axes[2].set_xlabel('Mean Score')
axes[2].set_ylabel('Frequency')
axes[2].legend()

# Plot 4: peer_support
axes[3].hist(clean_data['peer_support_mean'].dropna(), bins=20, color='steelblue', edgecolor='black', alpha=0.7)
axes[3].axvline(clean_data['peer_support_mean'].mean(), color='red', linestyle='dashed', linewidth=2, label='Mean')
axes[3].set_title('peer_support')
axes[3].set_xlabel('Mean Score')
axes[3].set_ylabel('Frequency')
axes[3].legend()

# Plot 5: alliance_total
axes[4].hist(clean_data['alliance_total_mean'].dropna(), bins=20, color='steelblue', edgecolor='black', alpha=0.7)
axes[4].axvline(clean_data['alliance_total_mean'].mean(), color='red', linestyle='dashed', linewidth=2, label='Mean')
axes[4].set_title('alliance_total')
axes[4].set_xlabel('Mean Score')
axes[4].set_ylabel('Frequency')
axes[4].legend()

plt.tight_layout()
plt.savefig('scale_distributions.png', dpi=300, bbox_inches='tight')
plt.show()

# Box plot: Compare flagged vs clean data
fig, axes = plt.subplots(3, 2, figsize=(12, 12))
axes = axes.flatten()

sns.boxplot(data=data, x='quality_flag', y='depersonalization_mean', ax=axes[0], palette={'OK': 'lightgreen', 'FLAGGED': 'salmon'})
axes[0].set_title('depersonalization by Quality Flag')
axes[0].set_xlabel('Quality Flag')
axes[0].set_ylabel('Mean Score')

sns.boxplot(data=data, x='quality_flag', y='supervision_rapport_mean', ax=axes[1], palette={'OK': 'lightgreen', 'FLAGGED': 'salmon'})
axes[1].set_title('supervision_rapport by Quality Flag')
axes[1].set_xlabel('Quality Flag')
axes[1].set_ylabel('Mean Score')

sns.boxplot(data=data, x='quality_flag', y='emotional_exhaustion_mean', ax=axes[2], palette={'OK': 'lightgreen', 'FLAGGED': 'salmon'})
axes[2].set_title('emotional_exhaustion by Quality Flag')
axes[2].set_xlabel('Quality Flag')
axes[2].set_ylabel('Mean Score')

sns.boxplot(data=data, x='quality_flag', y='peer_support_mean', ax=axes[3], palette={'OK': 'lightgreen', 'FLAGGED': 'salmon'})
axes[3].set_title('peer_support by Quality Flag')
axes[3].set_xlabel('Quality Flag')
axes[3].set_ylabel('Mean Score')

sns.boxplot(data=data, x='quality_flag', y='alliance_total_mean', ax=axes[4], palette={'OK': 'lightgreen', 'FLAGGED': 'salmon'})
axes[4].set_title('alliance_total by Quality Flag')
axes[4].set_xlabel('Quality Flag')
axes[4].set_ylabel('Mean Score')

plt.tight_layout()
plt.savefig('quality_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# ======================================================================
# CORRELATION MATRIX
# ======================================================================

scale_means = clean_data[['depersonalization_mean', 'supervision_rapport_mean', 'emotional_exhaustion_mean', 'peer_support_mean', 'alliance_total_mean']]

# Correlation matrix
print('\n=== Correlation Matrix ===')
cor_matrix = scale_means.corr()
print(cor_matrix.round(2))

# Correlation heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cor_matrix, annot=True, cmap='coolwarm', center=0, vmin=-1, vmax=1, square=True, linewidths=1)
plt.title('Scale Correlation Matrix')
plt.savefig('correlation_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# ======================================================================
# EXPORT RESULTS
# ======================================================================

# Save clean dataset
clean_data.to_csv('clean_data_python.csv', index=False)

# Create summary table
summary_stats = pd.DataFrame({
    'depersonalization': [
        clean_data['depersonalization_mean'].mean(),
        clean_data['depersonalization_mean'].std(),
        clean_data['depersonalization_mean'].min(),
        clean_data['depersonalization_mean'].max()
    ],
    'supervision_rapport': [
        clean_data['supervision_rapport_mean'].mean(),
        clean_data['supervision_rapport_mean'].std(),
        clean_data['supervision_rapport_mean'].min(),
        clean_data['supervision_rapport_mean'].max()
    ],
    'emotional_exhaustion': [
        clean_data['emotional_exhaustion_mean'].mean(),
        clean_data['emotional_exhaustion_mean'].std(),
        clean_data['emotional_exhaustion_mean'].min(),
        clean_data['emotional_exhaustion_mean'].max()
    ],
    'peer_support': [
        clean_data['peer_support_mean'].mean(),
        clean_data['peer_support_mean'].std(),
        clean_data['peer_support_mean'].min(),
        clean_data['peer_support_mean'].max()
    ],
    'alliance_total': [
        clean_data['alliance_total_mean'].mean(),
        clean_data['alliance_total_mean'].std(),
        clean_data['alliance_total_mean'].min(),
        clean_data['alliance_total_mean'].max()
    ]
},
index=['Mean', 'SD', 'Min', 'Max'])

print('\n=== Summary Statistics Table ===')
print(summary_stats.round(2))

# Save summary table
summary_stats.to_csv('summary_statistics.csv')

print('\n✓ Analysis complete! Results saved.')
